#!/bin/bash
#
# Use BuildTools to download and build latest Spigot.
#
set -e

VERSION="$1"
[ -z "$VERSION" ] && VERSION="latest"

# BuildTools
function install_buildtools
(
	[ -d "BuildTools" ] || mkdir "BuildTools"
	cd "BuildTools"

	# Download latest BuildTools
	wget -O BuildTools.jar "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"

	# Build
	echo "Java installed: $(which java)"
	java -jar BuildTools.jar --rev $VERSION
)

# bin
function install_bin
(
	[ -d "bin" ] || mkdir "bin"
	cd "bin"

	# Symlink into bin/
	[ -L "spigot.jar" ] && rm "spigot.jar"
	ln -s "$(ls -t "../BuildTools/spigot"*.jar | head -n1)" "spigot.jar"

	# Accept eula
	[ -f "eula.txt" ] || echo "eula=true" | tee "eula.txt"
)

# bin/plugins
function install_plugins
(
	[ -d "bin/plugins" ] || mkdir "bin/plugins"
	cd "bin/plugins"

	# Scrape the viaversion page to get its latest
    VIAVERSION_VERSION="latest"
	function scrape_viaversion
	{
		scrape="$(curl -s "https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/")"
		scrape="${scrape##*ViaVersion-}"
		scrape="${scrape%%-SNAPSHOT.jar*}"

		VIAVERSION_VERSION="${scrape}"
		echo "ViaVersion = $VIAVERSION_VERSION"
	}
	scrape_viaversion

	wget -O "Geyser-Spigot.jar" "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
	wget -O "floodgate-spigot.jar" "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
	wget -O "ViaVersion.jar" "https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-${VIAVERSION_VERSION}-SNAPSHOT.jar"
)

install_buildtools
install_bin
install_plugins

echo "Finished: $VERSION"
